#!/usr/bin/env python3
"""Regenerate book/_quarto.yml from state/progress.json and create any missing files:
chapter and appendix stubs, source-table placeholders, the preface, references, styles
and variables. Never overwrites an existing chapter, appendix or preface.

Usage:
  python3 scripts/sync_quarto.py
"""
from __future__ import annotations

import argparse

from common import STUB_MARKER, chapter_relpath, load_progress, root_from

STYLES_CSS = """/* Evidence badges: [company claim]{.ev}, [demo]{.ev}, [inference]{.ev} */
.ev {
  display: inline-block;
  font-size: 0.72em;
  line-height: 1.4;
  padding: 0 0.45em;
  margin: 0 0.15em;
  border: 1px solid currentColor;
  border-radius: 0.7em;
  opacity: 0.75;
  white-space: nowrap;
  vertical-align: 0.1em;
}
"""

EV_FILTER = """-- Evidence badges: [company claim]{.ev}, [demo]{.ev}, [inference]{.ev}.
-- HTML and EPUB style them with styles.css. Other formats (PDF) get an italic "(company claim)".
function Span(el)
  if el.classes:includes("ev") and not FORMAT:match("html") and not FORMAT:match("epub") then
    local out = pandoc.List({pandoc.Str("(")})
    out:extend(el.content)
    out:insert(pandoc.Str(")"))
    return pandoc.Emph(out)
  end
end
"""

REFERENCES_QMD = """# References {.unnumbered}

::: {#refs}
:::
"""

PREFACE_QMD = """# Preface {.unnumbered}

This book explains, from first principles, how an intelligent humanoid robot is built,
trained, deployed and improved after deployment. It assumes no background in robotics or
machine learning, and it goes all the way to the current frontier.

*Current as of {{< var current_as_of >}}.*

## How each concept is taught {.unnumbered}

Every concept and every component is explained in the same five layers:

1. **ELI5**: an everyday analogy that maps onto the real mechanism.
2. **First principles**: why it has to work this way.
3. **How it's actually done**: from the basic version to the frontier, with real numbers and named systems.
4. **Deployment lens**: what breaks in the field, what gets measured, and how it improves after launch.
5. **Sources**: every factual statement is cited.

## Evidence tags {.unnumbered}

Each chapter ends with a table of its sources and their evidence tags:

| Tag | Meaning |
|---|---|
| peer-reviewed | Published in a peer-reviewed venue |
| preprint | Public, but not yet peer-reviewed |
| technical report | A lab's technical report, model or dataset card, or official documentation |
| company claim | A company's statement about its own product, results or plans |
| demo | A video or live demonstration; the text says whether it was autonomous |
| standard | A standard or regulation |
| press | Journalism, used only where no primary source exists |

In the text, [company claim]{.ev}, [demo]{.ev} and [inference]{.ev} badges flag statements
that rest on a company's word, on a demonstration, or on the book's own reasoning.

## Running examples {.unnumbered}

Four tasks run through the book: a dinner for five with allergies, the kitchen reset that
follows it, an EV battery-pack connection station, and a greenhouse tomato harvest. They show
what each idea means for a real deployment.

## Research prompts {.unnumbered}

Each chapter ends with research prompts. The book deliberately does not answer them: they
point you to current evidence you will need to find and judge for yourself.
"""

GLOSSARY_QMD = """# Glossary {#sec-app-e}

Terms are defined where they first appear in the text. This list collects them in
alphabetical order, each with a pointer to the chapter that teaches it.

<!-- Add entries in definition-list form, keeping the list alphabetical:

Term
: One- or two-sentence definition. (@sec-chNN)
-->
"""


def q(s: str) -> str:
    return '"' + str(s).replace("\\", "\\\\").replace('"', '\\"') + '"'


def stub(title: str, label: str, status: str) -> str:
    return (f"# {title} {{#{label}}}\n\n{STUB_MARKER}\n\n"
            "::: {.callout-note title=\"In preparation\"}\n"
            f"This chapter has not been written yet (status: {status}).\n:::\n")


def main():
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--root")
    args = ap.parse_args()
    root = root_from(args.root)
    book = root / "book"
    progress = load_progress(root)
    meta = progress.get("book", {})
    created = []

    lines = [
        "# Generated by scripts/sync_quarto.py from state/progress.json. Edit progress.json, not this file.",
        "project:",
        "  type: book",
        "  output-dir: _book",
        "",
        "book:",
        f"  title: {q(meta.get('title', 'The Humanoid Lifecycle'))}",
        f"  subtitle: {q(meta.get('subtitle', ''))}",
        "  date: last-modified",
        '  date-format: "D MMMM YYYY"',
        "  search: true",
        "  chapters:",
        "    - index.qmd",
    ]
    appendices = []
    part_no = 0
    for part in progress["parts"]:
        if part.get("appendix"):
            for ch in part["chapters"]:
                rel = chapter_relpath(part, ch)
                appendices.append(rel)
                path = book / rel
                if not path.exists():
                    path.parent.mkdir(parents=True, exist_ok=True)
                    content = GLOSSARY_QMD if ch["slug"] == "glossary" else \
                        stub(ch["title"], f"sec-app-{ch['id'].lower()}", ch["status"])
                    path.write_text(content, encoding="utf-8")
                    created.append(rel)
            continue
        pid = part["id"].upper()
        display = part["title"] if pid == "P0" or not pid[1:].isdigit() else f"Part {int(pid[1:])} · {part['title']}"
        lines.append(f"    - part: {q(display)}")
        lines.append("      chapters:")
        part_no += 1
        for ch in part["chapters"]:
            rel = chapter_relpath(part, ch)
            lines.append(f"        - {rel}")
            path = book / rel
            if not path.exists():
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(stub(ch["title"], f"sec-ch{ch['id']}", ch["status"]), encoding="utf-8")
                created.append(rel)
            src = book / "chapters" / "_sources" / f"ch{ch['id']}.qmd"
            if not src.exists():
                src.parent.mkdir(parents=True, exist_ok=True)
                src.write_text("*No sources cited yet.*\n", encoding="utf-8")
    lines.append("    - references.qmd")
    if appendices:
        lines.append("  appendices:")
        lines += [f"    - {a}" for a in appendices]
    lines += [
        "",
        "bibliography: references.bib",
        "filters:",
        "  - ev-badges.lua",
    ]
    if (book / "ieee.csl").exists():
        lines.append("csl: ieee.csl")
    lines += [
        "lang: en-GB",
        "number-sections: true",
        "link-citations: true",
        "",
        "format:",
        "  html:",
        "    theme:",
        "      light: cosmo",
        "      dark: darkly",
        "    css: styles.css",
        "    toc: true",
        "    toc-depth: 3",
        "  pdf:",
        "    documentclass: scrreprt",
        "    papersize: a4",
        "    # Fonts must cover Greek (π0, τ0) and symbols (≤ ≈ →), or the PDF silently drops them.",
        "    # Install on macOS with: brew install --cask font-dejavu",
        '    mainfont: "DejaVu Serif"',
        '    sansfont: "DejaVu Sans"',
        '    monofont: "DejaVu Sans Mono"',
        "    fontsize: 10pt",
        "    toc-depth: 2",
        "    colorlinks: true",
        "  epub:",
        "    toc: true",
        "    css: styles.css",
        "",
    ]
    (book / "_quarto.yml").write_text("\n".join(lines), encoding="utf-8")

    defaults = {
        "index.qmd": PREFACE_QMD,
        "references.qmd": REFERENCES_QMD,
        "styles.css": STYLES_CSS,
        "ev-badges.lua": EV_FILTER,
        "references.bib": "% Managed by the bibliographer agent. One entry per source; see .claude/agents/bibliographer.md\n",
        "_variables.yml": 'current_as_of: "not yet set"\n',
    }
    for name, content in defaults.items():
        path = book / name
        if not path.exists():
            path.write_text(content, encoding="utf-8")
            created.append(name)
    print(f"wrote book/_quarto.yml ({part_no} parts, {len(appendices)} appendices)")
    if created:
        print(f"created {len(created)} files: " + ", ".join(created[:6]) + (" …" if len(created) > 6 else ""))


if __name__ == "__main__":
    main()
